spring: 
  application: 
    name: DocenteService
  datasource: 
    driver-class-name: drive-class-name=com.mysql.jdbc.Driver
    password: Corso12!
    server: 
      port: 8080
    url: "mysql://212.131.189.19:30016/corso12"
    username: Simone
  security: 
    name: user
    password: password
      
      