spring:
  datasource:
    driver-class-name: drive-class-name=com.mysql.jdbc.Driver
        url: mysql://212.131.189.19:30016/corso12
    username: Simone
     password: Corso12!
    
    server:      port: 8081
   
  security:    user:    name: user
    password: password
    
      application:    name: DocenteService
      
      